### ISSUE TITLE
selectDatabase Component Generator Error

### ISSUE THREAD

**Issue by Quinn-Donnelly** [Gods-Of-ACM/frontEnd#39]
## Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

The messages file in the selectDatabase component is invalid and causing the generate template command to fail when building.

## Steps to reproduce

 node ./internals/scripts/generate-templates-for-linting

**Comment by bsonge** [comment]
Changed SelectDatabase/messages.js to proper format, updated SelectDatabase/index.js to reflect the changes.

**Comment by Quinn-Donnelly** [comment]
#45 has resolved this issue
