### ISSUE TITLE
Connection for basic query to Backend

### ISSUE THREAD

**Issue by Quinn-Donnelly** [Gods-Of-ACM/frontEnd#41]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Connect the query for models into the view database component.

**Comment by Jubstron** [comment]
Issue resolved in #50
