### ISSUE TITLE
Search Bar Component

### ISSUE THREAD

**Issue by Quinn-Donnelly** [Gods-Of-ACM/frontEnd#42]
## Issue Type

- [ ] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

This component allows users to enter a data and select filters. The Search Bar component should take a handler that when the submit or search button is clicked it calls with the details of what the user has selected.

**Comment by Jubstron** [comment]
Issue resolved in #50
